data:
  block_size: 320 #hop size used in preprocessing
  duration: 2
  sampling_rate: 16000
  f0min: 80
  f0max: 1000
  train_path: /scratch/sghosh/datasets/DDSP/libri_esd/train
  valid_path: /scratch/sghosh/datasets/DDSP/libri_esd/val_extended
  emotion_files_wavlm6_path: /project/sghosh/dataset/ESD #has to be provided to use emo loss (i.e. if use_emo_loss: True)
  extension: 'flac'
model:
  n_mag_harmonic: 176
  n_mag_noise: 80
  n_harmonics: 150
  window: 'blackman-harris'
  convolve_power: 2
loss:
  n_ffts: [1024, 512, 256, 128, 64, 32]
  #n_ffts: [2048, 1024, 512, 256, 128, 64, 32]
  #n_ffts: [2048, 1024, 512, 256, 128, 64]
  #n_ffts: [2053, 1021, 509, 257, 127, 67]
  jitter: 0.1
  shimmer: 0.1
  use_kurtosis: False
  use_emo_loss: True
device: cuda
env:
  expdir: /cache/sghosh/exp/sad/

inference:
  batch_size: 684
  generate_files: True
train:
  batch_size: 684
  #batch_size: 48
  #batch_size: 1
  epochs: 1000
  interval_log: 10
  interval_save: 500
  interval_val: 500
  lr: 0.002